# Site settings
title: cjohnkim
email: john@jumpcue.co
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cjohnkim.com" # the base hostname & protocol for your site
twitter_username: cjohnkim

# Build settings
markdown: kramdown
